<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGQa8qrB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGQa8qrB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGQa8qrB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGQa8qrB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGQa8qrB\App_KernelDevDebugContainer([
    'container.build_hash' => 'GQa8qrB',
    'container.build_id' => '723817e8',
    'container.build_time' => 1685224561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGQa8qrB');
